# Generated by Django 6.0.4 on 2026-05-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(default='', max_length=100, unique=True)),
                ('user_email', models.EmailField(default='', max_length=254, unique=True)),
                ('user_password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
