"""
Django settings for albumDaSemana project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv('.env.local')

# Small helper to read env vars with fallback names and strip whitespace
def env_get(key, *alts, default=None):
    for k in (key,) + alts:
        v = os.getenv(k)
        if v is not None:
            return v.strip()
    return default

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
ALLOWED_HOSTS = env_get("DJANGO-ALLOWED-HOSTS", "DJANGO_ALLOWED_HOSTS", default="*").split(",")


SECRET_KEY = env_get("DJANGO-SECRET-KEY", "DJANGO_SECRET_KEY", default="unsafe-secret")
DEBUG = bool(int(env_get("DJANGO-DEBUG", "DJANGO_DEBUG", default="0")))
ALLOWED_HOSTS = env_get("DJANGO-ALLOWED-HOSTS", "DJANGO_ALLOWED_HOSTS", default="127.0.0.1").split(",")
# Fix name: Django expects CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = env_get(
    "DJANGO-CSRF-TRUSTED-ORIGINS", "DJANGO_CSRF_TRUSTED_ORIGINS",
    default="http://localhost:3000,http://localhost:5173"
).split(",")



# SECURITY WARNING: don't run with debug turned on in production!


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api_rest',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'albumDaSemana.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'albumDaSemana.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Prefer explicit Postgres env vars if provided (docker-compose uses POSTGRES_*)
        'ENGINE': 'django.db.backends.postgresql' if env_get('POSTGRES_DB') or env_get('DATABASE_ENGINE') else 'django.db.backends.sqlite3',
        'NAME': env_get('POSTGRES_DB', 'DJANGO-DB-NAME', 'DATABASE_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': env_get('POSTGRES_USER', 'DJANGO-DB-USER', 'DATABASE_USER', default=''),
        'PASSWORD': env_get('POSTGRES_PASSWORD', 'DJANGO-DB-PASSWORD', 'DATABASE_PASSWORD', default=''),
        'HOST': env_get('DATABASE_HOST', 'DJANGO-DB-HOST', 'POSTGRES_HOST', default='localhost'),
        'PORT': env_get('DATABASE_PORT', 'DJANGO-DB-PORT', 'POSTGRES_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
#CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:8000"
]

SPOTIFY_CLIENT_ID = env_get('SPOTIFY_CLIENT_ID', default='')
SPOTIFY_CLIENT_SECRET = env_get('SPOTIFY_CLIENT_SECRET', default='')
